version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 wait_for_db.py &&
             python3 manage.py runserver 0.0.0.0:8000
             python3 manage.py createsuperuser &&
             admin &&
             admin &&
             a@a.com &&
             admin@123 &&
             admin@123 &&
             "
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    # ports:
    #   - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A blog22 worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app

  # web-ser:
  #   build:
  #     context: client/
  #   # command: "npm i && npm start"
  #   ports:
  #     - "3001:3000"
volumes:
  pgdata: